version: '3.3'

volumes:
  mariadb:

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80

  app:
    build: .
    image: msterhuj/instants
    restart: always
    depends_on:
      - mariadb
    ports:
      - 80:80
    volumes:
      - ./:/var/www