version: '3.3'

volumes:
  mariadb:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb

  app:
    build: .
    image: msterhuj/instants
    ports:
      - 80:80
    volumes:
      - ./:/var/www